// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Secop.Infrastructure.Persistence;

#nullable disable

namespace Secop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408022500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Secop.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EnviadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_en");

                    b.Property<string>("ProcesoId")
                        .HasColumnType("text")
                        .HasColumnName("proceso_id");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("alertas", (string)null);
                });

            modelBuilder.Entity("Secop.Domain.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("ProcesoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proceso_id");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("RazonDescarte")
                        .HasColumnType("text")
                        .HasColumnName("razon_descarte");

                    b.Property<DateTime>("RegistradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_en");

                    b.Property<string>("Resultado")
                        .HasColumnType("text")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.ToTable("decisiones", (string)null);
                });

            modelBuilder.Entity("Secop.Domain.Entities.Proceso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DepartamentoEntidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento_entidad");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("NitEntidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nit_entidad");

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_entidad");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("presupuesto");

                    b.Property<DateTime>("SincronizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sincronizado_en");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlProceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_proceso");

                    b.HasKey("Id");

                    b.ToTable("procesos", (string)null);
                });

            modelBuilder.Entity("Secop.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("CapacidadFinanciera")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("capacidad_financiera");

                    b.PrimitiveCollection<List<string>>("CodigosUnspsc")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("codigos_unspsc");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.PrimitiveCollection<List<string>>("ExperienciaDescripcion")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("experiencia");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("RupVigencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rup_vigencia");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Secop.Domain.Entities.Puntaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Advertencias")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("advertencias");

                    b.Property<DateTime>("CalculadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculado_en");

                    b.Property<bool>("EsInhabilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_inhabilitado");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<string>("ProcesoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proceso_id");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<float>("PuntajeCompetencia")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_competencia");

                    b.Property<float>("PuntajeEntidad")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_entidad");

                    b.Property<float>("PuntajeRequisitos")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_requisitos");

                    b.Property<float>("PuntajeSimilitud")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_similitud");

                    b.Property<float>("PuntajeTiempo")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_tiempo");

                    b.Property<float>("PuntajeTotal")
                        .HasColumnType("real")
                        .HasColumnName("puntaje_total");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId", "ProveedorId")
                        .IsUnique();

                    b.ToTable("puntajes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
